import { execSync } from "node:child_process";
import { log } from "../logger.js";
import type { PipelineContext } from "../index.js";

export async function runFinalizePhase(ctx: PipelineContext): Promise<boolean> {
  const { issueId, issueTitle, branchName, project, reviewSummary, testVerdict } = ctx;
  const { repoPath, baseBranch } = project;

  // Push branch
  log("info", `Pushing branch ${branchName}`, issueId);
  try {
    execSync(`git push -u origin ${branchName}`, {
      cwd: repoPath,
      stdio: "pipe",
    });
  } catch (err) {
    log("error", `Git push failed: ${err}`, issueId);
    return false;
  }

  // Create PR
  log("info", "Creating pull request", issueId);
  const isWip = reviewSummary !== "All checks passed" || (testVerdict !== "PASS" && testVerdict !== undefined && testVerdict !== "Skipped");
  const titlePrefix = isWip ? "[WIP] " : "";
  const title = `${titlePrefix}${issueId}: ${issueTitle}`;

  const body = [
    "## Summary",
    `Automated implementation for ${issueId}.`,
    "",
    "## Quality Gate Results",
    `- **Code Review:** ${reviewSummary ?? "Not run"}`,
    `- **Visual Test:** ${testVerdict ?? "Not run"}`,
    `- **Review Iterations:** ${ctx.reviewIterations}`,
    `- **Test Attempts:** ${ctx.testAttempts}`,
    "",
    "---",
    "Generated by taky-ci pipeline",
  ].join("\n");

  try {
    const prUrl = execSync(
      `gh pr create --title "${title.replace(/"/g, '\\"')}" --base ${baseBranch} --body "${body.replace(/"/g, '\\"')}"`,
      {
        cwd: repoPath,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
      }
    ).trim();

    ctx.prUrl = prUrl;
    log("info", `PR created: ${prUrl}`, issueId);
  } catch (err) {
    log("error", `PR creation failed: ${err}`, issueId);
    return false;
  }

  return true;
}
